import jsPDF from "jspdf";
import type { Transaction } from "@/lib/types";

// ── Types ──────────────────────────────────────────────────────────────────

export type ExportPeriod = "current_month" | "custom_month" | "full_year";
export type ExportType = "monthly" | "annual";

export interface ExportOptions {
  includeCharts: boolean;
  includeCategoryAnalysis: boolean;
  includeRunningBalance: boolean;
  includeCompletionMetrics: boolean;
}

export interface ExportConfig {
  period: ExportPeriod;
  exportType: ExportType;
  options: ExportOptions;
  selectedMonth: string;
  selectedYear: number;
  transactions: Transaction[];
}

// ── Constants ──────────────────────────────────────────────────────────────

const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
const BRAND = "#2563eb";
const BRAND_LIGHT = "#dbeafe";
const TEXT_PRIMARY = "#0f172a";
const TEXT_SECONDARY = "#475569";
const TEXT_MUTED = "#94a3b8";
const DIVIDER = "#e2e8f0";
const BG_CARD = "#f8fafc";
const WHITE = "#ffffff";
const PALETTE = ["#2563eb", "#f59e0b", "#10b981", "#ef4444", "#8b5cf6", "#ec4899", "#06b6d4", "#64748b"];

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 20;
const CONTENT_W = PAGE_W - MARGIN * 2;

// ── Helpers ────────────────────────────────────────────────────────────────

function monthKey(date: Date) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace("#", "");
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

function formatCurrency(n: number): string {
  const prefix = n < 0 ? "-Rs " : "Rs ";
  return prefix + Math.abs(Math.round(n)).toLocaleString("en-IN");
}

function getMonthLabel(month: string): string {
  const [y, m] = month.split("-").map(Number);
  return `${MONTHS[m - 1]} ${y}`;
}

function rowCategory(row: Transaction): string {
  if (row.type === "income") return row.category?.trim() || "Income";
  if (row.notes?.trim()) return row.notes.trim();
  if (row.category?.trim()) return row.category.trim();
  return "Uncategorized";
}

// ── PDF Drawing Primitives ─────────────────────────────────────────────────

function setColor(doc: jsPDF, hex: string) {
  doc.setTextColor(...hexToRgb(hex));
}

function drawLine(doc: jsPDF, y: number) {
  doc.setDrawColor(...hexToRgb(DIVIDER));
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
}

function drawRect(doc: jsPDF, x: number, y: number, w: number, h: number, fill: string, radius = 0) {
  doc.setFillColor(...hexToRgb(fill));
  if (radius > 0) {
    doc.roundedRect(x, y, w, h, radius, radius, "F");
  } else {
    doc.rect(x, y, w, h, "F");
  }
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    setColor(doc, TEXT_MUTED);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_W / 2, PAGE_H - 10, { align: "center" });
    doc.text("Generated by Barakify", MARGIN, PAGE_H - 10);
    doc.text(new Date().toLocaleDateString("en-IN"), PAGE_W - MARGIN, PAGE_H - 10, { align: "right" });
  }
}

function needsNewPage(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > PAGE_H - 20) {
    doc.addPage();
    return 28;
  }
  return y;
}

// ── Donut Chart Drawing ────────────────────────────────────────────────────

function drawDonutChart(
  doc: jsPDF,
  cx: number,
  cy: number,
  outerR: number,
  innerR: number,
  slices: Array<{ pct: number; color: string }>
) {
  let startAngle = -Math.PI / 2;
  for (const slice of slices) {
    if (slice.pct <= 0) continue;
    const sweepAngle = slice.pct * 2 * Math.PI;
    const endAngle = startAngle + sweepAngle;
    const steps = Math.max(20, Math.ceil(sweepAngle * 40));
    const points: Array<[number, number]> = [];
    for (let i = 0; i <= steps; i++) {
      const a = startAngle + (sweepAngle * i) / steps;
      points.push([cx + outerR * Math.cos(a), cy + outerR * Math.sin(a)]);
    }
    for (let i = steps; i >= 0; i--) {
      const a = startAngle + (sweepAngle * i) / steps;
      points.push([cx + innerR * Math.cos(a), cy + innerR * Math.sin(a)]);
    }
    doc.setFillColor(...hexToRgb(slice.color));
    const first = points[0];
    let pathStr = `${first[0]} ${first[1]} m`;
    for (let i = 1; i < points.length; i++) {
      pathStr += ` ${points[i][0]} ${points[i][1]} l`;
    }
    pathStr += " h f";

    // Use polygon approach
    const xs = points.map(p => p[0]);
    const ys = points.map(p => p[1]);
    // jsPDF doesn't have a polygon fill API, so draw via lines
    // Using triangle fan approach instead
    drawFilledArcSegment(doc, cx, cy, outerR, innerR, startAngle, endAngle, slice.color);
    startAngle = endAngle;
  }
}

function drawFilledArcSegment(
  doc: jsPDF,
  cx: number,
  cy: number,
  outerR: number,
  innerR: number,
  startAngle: number,
  endAngle: number,
  color: string
) {
  doc.setFillColor(...hexToRgb(color));
  const sweepAngle = endAngle - startAngle;
  const steps = Math.max(24, Math.ceil(Math.abs(sweepAngle) * 30));

  // Build the path as a series of triangles from the outer arc to inner arc
  for (let i = 0; i < steps; i++) {
    const a1 = startAngle + (sweepAngle * i) / steps;
    const a2 = startAngle + (sweepAngle * (i + 1)) / steps;
    const ox1 = cx + outerR * Math.cos(a1);
    const oy1 = cy + outerR * Math.sin(a1);
    const ox2 = cx + outerR * Math.cos(a2);
    const oy2 = cy + outerR * Math.sin(a2);
    const ix1 = cx + innerR * Math.cos(a1);
    const iy1 = cy + innerR * Math.sin(a1);
    const ix2 = cx + innerR * Math.cos(a2);
    const iy2 = cy + innerR * Math.sin(a2);
    doc.triangle(ox1, oy1, ox2, oy2, ix1, iy1, "F");
    doc.triangle(ox2, oy2, ix2, iy2, ix1, iy1, "F");
  }
}

// ── Bar Chart Drawing ──────────────────────────────────────────────────────

function drawBarChart(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  data: Array<{ label: string; value: number; color: string }>
) {
  const maxVal = Math.max(...data.map(d => d.value), 1);
  const barW = Math.min(12, (w - 10) / data.length - 2);
  const gap = (w - barW * data.length) / (data.length + 1);

  // Y-axis baseline
  drawLine(doc, y + h);

  for (let i = 0; i < data.length; i++) {
    const barH = Math.max(1, (data[i].value / maxVal) * (h - 5));
    const bx = x + gap + i * (barW + gap);
    const by = y + h - barH;
    drawRect(doc, bx, by, barW, barH, data[i].color, 1.5);

    // Label
    doc.setFontSize(6);
    setColor(doc, TEXT_MUTED);
    doc.text(data[i].label, bx + barW / 2, y + h + 5, { align: "center" });
  }
}

// ── Cover Page ─────────────────────────────────────────────────────────────

function renderCoverPage(doc: jsPDF, config: ExportConfig) {
  // Background gradient band
  drawRect(doc, 0, 0, PAGE_W, PAGE_H, WHITE);
  drawRect(doc, 0, 0, PAGE_W, 130, BRAND);

  // Decorative circle
  doc.setFillColor(...hexToRgb("#3b82f6"));
  doc.circle(PAGE_W - 30, 30, 60, "F");
  doc.setFillColor(...hexToRgb("#1d4ed8"));
  doc.circle(30, 110, 40, "F");

  // Logo text
  doc.setFontSize(14);
  setColor(doc, WHITE);
  doc.setFont("helvetica", "bold");
  doc.text("BARAKIFY", MARGIN, 36);

  // Title
  doc.setFontSize(34);
  doc.text("Financial Report", MARGIN, 72);

  // Period
  doc.setFontSize(16);
  doc.setFont("helvetica", "normal");
  let periodLabel: string;
  if (config.exportType === "annual") {
    periodLabel = `Year ${config.selectedYear}`;
  } else {
    periodLabel = getMonthLabel(config.selectedMonth);
  }
  doc.text(periodLabel, MARGIN, 92);

  // Subtext
  doc.setFontSize(11);
  doc.text(config.exportType === "annual" ? "Annual Financial Report" : "Monthly Financial Summary", MARGIN, 106);

  // Below band info
  let y = 160;
  doc.setFontSize(11);
  setColor(doc, TEXT_SECONDARY);
  doc.text("Generated On", MARGIN, y);
  doc.setFontSize(14);
  setColor(doc, TEXT_PRIMARY);
  doc.setFont("helvetica", "bold");
  y += 8;
  doc.text(new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }), MARGIN, y);

  y += 20;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  setColor(doc, TEXT_SECONDARY);
  doc.text("Prepared By", MARGIN, y);
  doc.setFontSize(14);
  setColor(doc, TEXT_PRIMARY);
  doc.setFont("helvetica", "bold");
  y += 8;
  doc.text("Barakify", MARGIN, y);

  // Bottom tagline
  doc.setFontSize(9);
  setColor(doc, TEXT_MUTED);
  doc.setFont("helvetica", "normal");
  doc.text("Personal Financial Intelligence", MARGIN, PAGE_H - 30);
}

// ── Monthly Summary Pages ──────────────────────────────────────────────────

function getMonthData(transactions: Transaction[], month: string) {
  const rows = transactions.filter(t => monthKey(new Date(t.transaction_date)) === month);
  const income = rows.filter(t => t.type === "income");
  const expenses = rows.filter(t => t.type === "expense");
  const totalIncome = income.reduce((s, t) => s + t.amount, 0);
  const totalExpense = expenses.reduce((s, t) => s + t.amount, 0);
  const savings = totalIncome - totalExpense;
  const paidCount = expenses.filter(t => t.is_paid).length;
  const completion = expenses.length > 0 ? paidCount / expenses.length : 0;

  const expenseByCategory: Record<string, number> = {};
  for (const row of expenses) {
    const cat = rowCategory(row);
    expenseByCategory[cat] = (expenseByCategory[cat] ?? 0) + row.amount;
  }

  const incomeByCategory: Record<string, number> = {};
  for (const row of income) {
    const cat = row.category?.trim() || "Income";
    incomeByCategory[cat] = (incomeByCategory[cat] ?? 0) + row.amount;
  }

  return { income, expenses, totalIncome, totalExpense, savings, paidCount, completion, expenseByCategory, incomeByCategory };
}

function computeRunningBalance(transactions: Transaction[], upToMonth: string): number {
  const sorted = [...transactions].sort((a, b) => a.transaction_date.localeCompare(b.transaction_date));
  let balance = 0;
  for (const t of sorted) {
    const mk = monthKey(new Date(t.transaction_date));
    if (mk > upToMonth) break;
    balance += t.type === "income" ? t.amount : -t.amount;
  }
  return balance;
}

function renderKPICard(doc: jsPDF, x: number, y: number, w: number, label: string, value: string, accent = false) {
  drawRect(doc, x, y, w, 28, accent ? BRAND : BG_CARD, 4);
  doc.setFontSize(8);
  setColor(doc, accent ? BRAND_LIGHT : TEXT_SECONDARY);
  doc.setFont("helvetica", "normal");
  doc.text(label, x + 6, y + 9);
  doc.setFontSize(14);
  setColor(doc, accent ? WHITE : TEXT_PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.text(value, x + 6, y + 22);
}

function renderFinancialSnapshot(doc: jsPDF, config: ExportConfig, month: string) {
  doc.addPage();
  const data = getMonthData(config.transactions, month);
  const balance = config.options.includeRunningBalance ? computeRunningBalance(config.transactions, month) : null;

  let y = 24;

  // Header
  doc.setFontSize(8);
  setColor(doc, BRAND);
  doc.setFont("helvetica", "bold");
  doc.text("FINANCIAL SNAPSHOT", MARGIN, y);
  y += 5;
  doc.setFontSize(16);
  setColor(doc, TEXT_PRIMARY);
  doc.text(getMonthLabel(month), MARGIN, y + 6);
  y += 16;
  drawLine(doc, y);
  y += 10;

  // KPI Cards — 2 per row
  const cardW = (CONTENT_W - 6) / 2;
  renderKPICard(doc, MARGIN, y, cardW, "Total Income", formatCurrency(data.totalIncome));
  renderKPICard(doc, MARGIN + cardW + 6, y, cardW, "Total Expenses", formatCurrency(data.totalExpense));
  y += 34;
  renderKPICard(doc, MARGIN, y, cardW, "Net Savings", formatCurrency(data.savings), true);
  if (balance !== null) {
    renderKPICard(doc, MARGIN + cardW + 6, y, cardW, "Running Balance", formatCurrency(balance));
  } else if (config.options.includeCompletionMetrics) {
    renderKPICard(doc, MARGIN + cardW + 6, y, cardW, "Expense Completion", `${Math.round(data.completion * 100)}%`);
  }
  y += 34;

  if (config.options.includeCompletionMetrics && balance !== null) {
    renderKPICard(doc, MARGIN, y, cardW, "Expense Completion", `${Math.round(data.completion * 100)}%`);
    renderKPICard(doc, MARGIN + cardW + 6, y, cardW, "Paid Expenses", `${data.paidCount} of ${data.expenses.length}`);
    y += 34;
  }

  return y;
}

function renderExpenseBreakdown(doc: jsPDF, config: ExportConfig, month: string) {
  doc.addPage();
  const data = getMonthData(config.transactions, month);
  const entries = Object.entries(data.expenseByCategory).sort((a, b) => b[1] - a[1]);
  const total = data.totalExpense;

  let y = 24;

  doc.setFontSize(8);
  setColor(doc, BRAND);
  doc.setFont("helvetica", "bold");
  doc.text("EXPENSE BREAKDOWN", MARGIN, y);
  y += 5;
  doc.setFontSize(16);
  setColor(doc, TEXT_PRIMARY);
  doc.text(getMonthLabel(month), MARGIN, y + 6);
  y += 16;
  drawLine(doc, y);
  y += 10;

  // Donut chart
  if (config.options.includeCharts && entries.length > 0) {
    const chartCX = PAGE_W / 2;
    const chartCY = y + 30;
    const slices = entries.map(([, val], i) => ({
      pct: total > 0 ? val / total : 0,
      color: PALETTE[i % PALETTE.length]
    }));
    drawDonutChart(doc, chartCX, chartCY, 26, 14, slices);

    // Center total
    doc.setFontSize(9);
    setColor(doc, TEXT_PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.text(formatCurrency(total), chartCX, chartCY + 1, { align: "center" });
    doc.setFontSize(6);
    setColor(doc, TEXT_MUTED);
    doc.setFont("helvetica", "normal");
    doc.text("Total", chartCX, chartCY + 5, { align: "center" });

    y += 66;
  }

  // Table
  if (config.options.includeCategoryAnalysis && entries.length > 0) {
    y = needsNewPage(doc, y, 20);

    // Header
    drawRect(doc, MARGIN, y, CONTENT_W, 8, BG_CARD, 2);
    doc.setFontSize(7);
    setColor(doc, TEXT_SECONDARY);
    doc.setFont("helvetica", "bold");
    doc.text("Category", MARGIN + 4, y + 5.5);
    doc.text("Amount", MARGIN + CONTENT_W - 50, y + 5.5, { align: "right" });
    doc.text("Share", MARGIN + CONTENT_W - 4, y + 5.5, { align: "right" });
    y += 10;

    for (let i = 0; i < entries.length; i++) {
      y = needsNewPage(doc, y, 9);
      const [cat, val] = entries[i];
      const pct = total > 0 ? (val / total) * 100 : 0;

      if (i % 2 === 0) {
        drawRect(doc, MARGIN, y - 1, CONTENT_W, 8, BG_CARD);
      }

      // Color dot
      doc.setFillColor(...hexToRgb(PALETTE[i % PALETTE.length]));
      doc.circle(MARGIN + 6, y + 3, 1.5, "F");

      doc.setFontSize(8);
      setColor(doc, TEXT_PRIMARY);
      doc.setFont("helvetica", "normal");
      doc.text(cat, MARGIN + 12, y + 5);
      doc.text(formatCurrency(val), MARGIN + CONTENT_W - 50, y + 5, { align: "right" });
      setColor(doc, TEXT_SECONDARY);
      doc.text(`${Math.round(pct)}%`, MARGIN + CONTENT_W - 4, y + 5, { align: "right" });

      // Progress bar
      const barX = MARGIN + CONTENT_W - 46;
      const barW = 30;
      drawRect(doc, barX, y + 1, barW, 3, "#e2e8f0", 1);
      drawRect(doc, barX, y + 1, Math.max(1, barW * (pct / 100)), 3, PALETTE[i % PALETTE.length], 1);

      y += 9;
    }
  }

  return y;
}

function renderIncomeBreakdown(doc: jsPDF, config: ExportConfig, month: string) {
  doc.addPage();
  const data = getMonthData(config.transactions, month);
  const entries = Object.entries(data.incomeByCategory).sort((a, b) => b[1] - a[1]);

  let y = 24;

  doc.setFontSize(8);
  setColor(doc, BRAND);
  doc.setFont("helvetica", "bold");
  doc.text("INCOME BREAKDOWN", MARGIN, y);
  y += 5;
  doc.setFontSize(16);
  setColor(doc, TEXT_PRIMARY);
  doc.text(getMonthLabel(month), MARGIN, y + 6);
  y += 16;
  drawLine(doc, y);
  y += 10;

  if (entries.length === 0) {
    doc.setFontSize(10);
    setColor(doc, TEXT_MUTED);
    doc.setFont("helvetica", "normal");
    doc.text("No income data for this period.", MARGIN, y + 5);
    return y + 10;
  }

  // Table header
  drawRect(doc, MARGIN, y, CONTENT_W, 8, BG_CARD, 2);
  doc.setFontSize(7);
  setColor(doc, TEXT_SECONDARY);
  doc.setFont("helvetica", "bold");
  doc.text("Source", MARGIN + 4, y + 5.5);
  doc.text("Amount", MARGIN + CONTENT_W - 4, y + 5.5, { align: "right" });
  y += 10;

  for (let i = 0; i < entries.length; i++) {
    y = needsNewPage(doc, y, 9);
    const [cat, val] = entries[i];

    if (i % 2 === 0) {
      drawRect(doc, MARGIN, y - 1, CONTENT_W, 8, BG_CARD);
    }

    doc.setFontSize(8);
    setColor(doc, TEXT_PRIMARY);
    doc.setFont("helvetica", "normal");
    doc.text(cat, MARGIN + 4, y + 5);
    doc.setFont("helvetica", "bold");
    doc.text(formatCurrency(val), MARGIN + CONTENT_W - 4, y + 5, { align: "right" });

    y += 9;
  }

  // Total
  y += 3;
  drawLine(doc, y);
  y += 6;
  doc.setFontSize(9);
  setColor(doc, TEXT_PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.text("Total Income", MARGIN + 4, y + 1);
  doc.text(formatCurrency(data.totalIncome), MARGIN + CONTENT_W - 4, y + 1, { align: "right" });

  return y + 10;
}

// ── Annual Report Pages ────────────────────────────────────────────────────

function renderAnnualPerformanceTable(doc: jsPDF, config: ExportConfig) {
  doc.addPage();
  let y = 24;

  doc.setFontSize(8);
  setColor(doc, BRAND);
  doc.setFont("helvetica", "bold");
  doc.text("MONTHLY PERFORMANCE", MARGIN, y);
  y += 5;
  doc.setFontSize(16);
  setColor(doc, TEXT_PRIMARY);
  doc.text(`Year ${config.selectedYear}`, MARGIN, y + 6);
  y += 16;
  drawLine(doc, y);
  y += 10;

  // Table header
  drawRect(doc, MARGIN, y, CONTENT_W, 8, BRAND, 2);
  doc.setFontSize(7);
  setColor(doc, WHITE);
  doc.setFont("helvetica", "bold");
  doc.text("Month", MARGIN + 4, y + 5.5);
  doc.text("Income", MARGIN + 60, y + 5.5, { align: "right" });
  doc.text("Expenses", MARGIN + 100, y + 5.5, { align: "right" });
  doc.text("Savings", MARGIN + 140, y + 5.5, { align: "right" });
  doc.text("Rate", MARGIN + CONTENT_W - 4, y + 5.5, { align: "right" });
  y += 10;

  let grandIncome = 0, grandExpense = 0;

  for (let m = 1; m <= 12; m++) {
    const mk = `${config.selectedYear}-${String(m).padStart(2, "0")}`;
    const data = getMonthData(config.transactions, mk);
    const savings = data.totalIncome - data.totalExpense;
    const rate = data.totalIncome > 0 ? (savings / data.totalIncome) * 100 : 0;
    grandIncome += data.totalIncome;
    grandExpense += data.totalExpense;

    y = needsNewPage(doc, y, 9);
    if (m % 2 === 0) drawRect(doc, MARGIN, y - 1, CONTENT_W, 8, BG_CARD);

    doc.setFontSize(7.5);
    setColor(doc, TEXT_PRIMARY);
    doc.setFont("helvetica", "normal");
    doc.text(MONTHS[m - 1], MARGIN + 4, y + 5);
    doc.text(data.totalIncome > 0 ? formatCurrency(data.totalIncome) : "—", MARGIN + 60, y + 5, { align: "right" });
    doc.text(data.totalExpense > 0 ? formatCurrency(data.totalExpense) : "—", MARGIN + 100, y + 5, { align: "right" });
    setColor(doc, savings >= 0 ? "#059669" : "#dc2626");
    doc.text(data.totalIncome > 0 || data.totalExpense > 0 ? formatCurrency(savings) : "—", MARGIN + 140, y + 5, { align: "right" });
    setColor(doc, TEXT_SECONDARY);
    doc.text(data.totalIncome > 0 ? `${Math.round(rate)}%` : "—", MARGIN + CONTENT_W - 4, y + 5, { align: "right" });
    y += 9;
  }

  // Grand total row
  y += 2;
  drawRect(doc, MARGIN, y - 1, CONTENT_W, 9, BRAND, 2);
  doc.setFontSize(8);
  setColor(doc, WHITE);
  doc.setFont("helvetica", "bold");
  doc.text("Total", MARGIN + 4, y + 5.5);
  doc.text(formatCurrency(grandIncome), MARGIN + 60, y + 5.5, { align: "right" });
  doc.text(formatCurrency(grandExpense), MARGIN + 100, y + 5.5, { align: "right" });
  doc.text(formatCurrency(grandIncome - grandExpense), MARGIN + 140, y + 5.5, { align: "right" });
  const grandRate = grandIncome > 0 ? ((grandIncome - grandExpense) / grandIncome) * 100 : 0;
  doc.text(`${Math.round(grandRate)}%`, MARGIN + CONTENT_W - 4, y + 5.5, { align: "right" });

  return y + 14;
}

function renderAnnualTrends(doc: jsPDF, config: ExportConfig) {
  doc.addPage();
  let y = 24;

  doc.setFontSize(8);
  setColor(doc, BRAND);
  doc.setFont("helvetica", "bold");
  doc.text("ANNUAL TRENDS", MARGIN, y);
  y += 5;
  doc.setFontSize(16);
  setColor(doc, TEXT_PRIMARY);
  doc.text(`Year ${config.selectedYear}`, MARGIN, y + 6);
  y += 16;
  drawLine(doc, y);
  y += 10;

  const monthData: Array<{ label: string; income: number; expense: number; savings: number }> = [];
  for (let m = 1; m <= 12; m++) {
    const mk = `${config.selectedYear}-${String(m).padStart(2, "0")}`;
    const data = getMonthData(config.transactions, mk);
    monthData.push({
      label: MONTHS[m - 1].slice(0, 3),
      income: data.totalIncome,
      expense: data.totalExpense,
      savings: data.totalIncome - data.totalExpense
    });
  }

  // Expense Trend bar chart
  doc.setFontSize(10);
  setColor(doc, TEXT_PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.text("Expense Trend", MARGIN, y + 4);
  y += 10;

  drawBarChart(doc, MARGIN, y, CONTENT_W, 45, monthData.map(d => ({
    label: d.label,
    value: d.expense,
    color: "#ef4444"
  })));
  y += 60;

  // Savings Trend bar chart
  doc.setFontSize(10);
  setColor(doc, TEXT_PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.text("Savings Trend", MARGIN, y + 4);
  y += 10;

  drawBarChart(doc, MARGIN, y, CONTENT_W, 45, monthData.map(d => ({
    label: d.label,
    value: Math.max(0, d.savings),
    color: "#10b981"
  })));
  y += 60;

  return y;
}

function renderAnnualSummary(doc: jsPDF, config: ExportConfig) {
  doc.addPage();
  let y = 24;

  doc.setFontSize(8);
  setColor(doc, BRAND);
  doc.setFont("helvetica", "bold");
  doc.text("YEAR SUMMARY", MARGIN, y);
  y += 5;
  doc.setFontSize(16);
  setColor(doc, TEXT_PRIMARY);
  doc.text(`Year ${config.selectedYear}`, MARGIN, y + 6);
  y += 16;
  drawLine(doc, y);
  y += 10;

  let totalIncome = 0, totalExpense = 0;
  let highestSpendMonth = "", highestSpend = 0;
  let highestSaveMonth = "", highestSave = -Infinity;
  const monthlySavings: number[] = [];

  for (let m = 1; m <= 12; m++) {
    const mk = `${config.selectedYear}-${String(m).padStart(2, "0")}`;
    const data = getMonthData(config.transactions, mk);
    totalIncome += data.totalIncome;
    totalExpense += data.totalExpense;
    const savings = data.totalIncome - data.totalExpense;
    monthlySavings.push(savings);
    if (data.totalExpense > highestSpend) { highestSpend = data.totalExpense; highestSpendMonth = MONTHS[m - 1]; }
    if (savings > highestSave && (data.totalIncome > 0 || data.totalExpense > 0)) { highestSave = savings; highestSaveMonth = MONTHS[m - 1]; }
  }

  const avgSavings = monthlySavings.filter((_, i) => {
    const mk = `${config.selectedYear}-${String(i + 1).padStart(2, "0")}`;
    const d = getMonthData(config.transactions, mk);
    return d.totalIncome > 0 || d.totalExpense > 0;
  });
  const avgMonthlySavings = avgSavings.length > 0 ? avgSavings.reduce((s, v) => s + v, 0) / avgSavings.length : 0;
  const yearEndBalance = computeRunningBalance(config.transactions, `${config.selectedYear}-12`);

  // Large KPI cards
  const cardW = (CONTENT_W - 6) / 2;
  renderKPICard(doc, MARGIN, y, cardW, "Total Income", formatCurrency(totalIncome));
  renderKPICard(doc, MARGIN + cardW + 6, y, cardW, "Total Expenses", formatCurrency(totalExpense));
  y += 34;

  renderKPICard(doc, MARGIN, y, cardW, "Net Savings", formatCurrency(totalIncome - totalExpense), true);
  renderKPICard(doc, MARGIN + cardW + 6, y, cardW, "Year-End Balance", formatCurrency(yearEndBalance));
  y += 34;

  renderKPICard(doc, MARGIN, y, cardW, "Avg Monthly Savings", formatCurrency(avgMonthlySavings));
  renderKPICard(doc, MARGIN + cardW + 6, y, cardW, "Savings Rate", `${totalIncome > 0 ? Math.round(((totalIncome - totalExpense) / totalIncome) * 100) : 0}%`);
  y += 40;

  // Highlights
  drawLine(doc, y);
  y += 10;

  doc.setFontSize(10);
  setColor(doc, TEXT_PRIMARY);
  doc.setFont("helvetica", "bold");
  doc.text("Highlights", MARGIN, y + 2);
  y += 12;

  const highlights = [
    ["Highest Spending Month", highestSpendMonth ? `${highestSpendMonth} (${formatCurrency(highestSpend)})` : "—"],
    ["Highest Saving Month", highestSaveMonth ? `${highestSaveMonth} (${formatCurrency(highestSave)})` : "—"],
    ["Active Months", `${avgSavings.length} of 12`],
  ];

  for (const [label, value] of highlights) {
    doc.setFontSize(8);
    setColor(doc, TEXT_SECONDARY);
    doc.setFont("helvetica", "normal");
    doc.text(label, MARGIN + 4, y + 4);
    setColor(doc, TEXT_PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.text(value, MARGIN + CONTENT_W - 4, y + 4, { align: "right" });
    y += 10;
  }

  // Top spending categories (annual)
  if (config.options.includeCategoryAnalysis) {
    y += 5;
    drawLine(doc, y);
    y += 10;

    doc.setFontSize(10);
    setColor(doc, TEXT_PRIMARY);
    doc.setFont("helvetica", "bold");
    doc.text("Top Spending Categories", MARGIN, y + 2);
    y += 12;

    const annualCategories: Record<string, number> = {};
    for (let m = 1; m <= 12; m++) {
      const mk = `${config.selectedYear}-${String(m).padStart(2, "0")}`;
      const data = getMonthData(config.transactions, mk);
      for (const [cat, val] of Object.entries(data.expenseByCategory)) {
        annualCategories[cat] = (annualCategories[cat] ?? 0) + val;
      }
    }
    const topCats = Object.entries(annualCategories).sort((a, b) => b[1] - a[1]).slice(0, 8);

    for (let i = 0; i < topCats.length; i++) {
      y = needsNewPage(doc, y, 9);
      const [cat, val] = topCats[i];
      const pct = totalExpense > 0 ? (val / totalExpense) * 100 : 0;

      if (i % 2 === 0) drawRect(doc, MARGIN, y - 1, CONTENT_W, 8, BG_CARD);

      doc.setFillColor(...hexToRgb(PALETTE[i % PALETTE.length]));
      doc.circle(MARGIN + 6, y + 3, 1.5, "F");

      doc.setFontSize(8);
      setColor(doc, TEXT_PRIMARY);
      doc.setFont("helvetica", "normal");
      doc.text(cat, MARGIN + 12, y + 5);
      doc.setFont("helvetica", "bold");
      doc.text(formatCurrency(val), MARGIN + CONTENT_W - 40, y + 5, { align: "right" });
      setColor(doc, TEXT_SECONDARY);
      doc.setFont("helvetica", "normal");
      doc.text(`${Math.round(pct)}%`, MARGIN + CONTENT_W - 4, y + 5, { align: "right" });
      y += 9;
    }
  }

  return y;
}

// ── Main Export Function ───────────────────────────────────────────────────

export function generatePDF(config: ExportConfig) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // Cover page
  renderCoverPage(doc, config);

  if (config.exportType === "monthly") {
    renderFinancialSnapshot(doc, config, config.selectedMonth);
    renderExpenseBreakdown(doc, config, config.selectedMonth);
    renderIncomeBreakdown(doc, config, config.selectedMonth);
  } else {
    // Annual report
    renderFinancialSnapshot(doc, config, `${config.selectedYear}-01`);
    renderAnnualPerformanceTable(doc, config);
    if (config.options.includeCharts) {
      renderAnnualTrends(doc, config);
    }
    renderAnnualSummary(doc, config);
  }

  addFooter(doc);

  // Generate filename
  let filename: string;
  if (config.exportType === "monthly") {
    filename = `Barakify-Report-${config.selectedMonth}.pdf`;
  } else {
    filename = `Barakify-Annual-Report-${config.selectedYear}.pdf`;
  }

  doc.save(filename);
}
